// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrrmrpdzjzszuopuadjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhycm1ycGR6anpzenVvcHVhZGp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MzA1MjUsImV4cCI6MjA3MDIwNjUyNX0.SGRaT-9M34iWfDtU_U03GlS6teozGngounId10eifTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});